services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    restart: always
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysqldb:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      retries: 5
      start_period: 20s
      timeout: 10s
    networks:
      - midas-network 

  web:
    stdin_open: true
    tty: true
    container_name: web
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./src/:/opt/app/src
      - ./prisma:/opt/app/prisma
    depends_on:
      mysqldb:
        condition: service_healthy
    ports:
      - '${API_PORT}:${API_PORT}'
      - '${PRISMA_STUDIO_PORT}:${PRISMA_STUDIO_PORT}'
    env_file:
      - .env
    environment:
      PORT: ${API_PORT}
    healthcheck:
      test: curl --fail web:${API_PORT}/health || exit 1
      interval: 5s
      retries: 10
      start_period: 30s
      timeout: 10s
    networks:
      - midas-network

networks:
  midas-network:
    name: midas-network
    driver: bridge

volumes:
  mysqldb:
  